name: flexpath
description: "a job listing project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter_animate: ^4.1.1+1
  font_awesome_flutter: ^10.5.0
  cached_network_image: ^3.3.1
  animate_do: ^4.2.0
  animations: ^2.0.0
  intl: ^0.17.0
  supabase_flutter: ^2.8.1
  image_picker: ^1.1.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^2.1.0
  flutter_social_button: 1.1.6+1
  # Add more dependencies here if needed, for example:
  # provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/loading_animation.json
    - assets/flexpath_logo.png
    - assets/google_icon.png
    - assets/facebook_icon.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
